name: PowerShell Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run PSCore cmdlet
      shell: pwsh
      run: ls
    
    - name: Run bash command (EnvVar)
      shell: bash
      run: env
      
      
    - name: Run PSCore script from repo
      shell: pwsh
      run: .\.github\workflows\scripts\helloworld.ps1
